/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CalendarCard: typeof import('./components/CalendarCard.vue')['default']
    CalendarDays: typeof import('./components/CalendarDays.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MealPlanner: typeof import('./components/MealPlanner.vue')['default']
    RecipeList: typeof import('./components/RecipesList.vue')['default']
    RecipesList: typeof import('./components/RecipesList.vue')['default']
    RecipeTable: typeof import('./components/RecipeTable.vue')['default']
    RecipeView: typeof import('./views/RecipesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
